from tkinter import *
lvl_pg=Tk()
lvl_pg.geometry("500x500")
l1=Label(lvl_pg,text="Game overview")
l1.grid(row=0, column=0 ,columnspan=3)
level1=Button(lvl_pg, text="Level 1", padx=40,)
level1.grid(row=1, column=0 )
level2=Button(lvl_pg, text="Level 2", padx=40 )
level2.grid(row=1, column=1)
level3=Button(lvl_pg, text="Level 3", state=DISABLED, padx=40)
level3.grid(row=1, column=2)
level4=Button(lvl_pg, text="Level 4", state=DISABLED, padx=40)
level4.grid(row=2, column=0)
level5=Button(lvl_pg, text="Level 5", state=DISABLED, padx=40)
level5.grid(row=2, column=1)
level6=Button(lvl_pg, text="Level 6", padx=40)
level6.grid(row=2, column=2)
level7=Button(lvl_pg, text="Level 7", state=DISABLED, padx=40)
level7.grid(row=3, column=0)
level8=Button(lvl_pg, text="Level 8", state=DISABLED, padx=40)
level8.grid(row=3, column=1)
level9=Button(lvl_pg, text="Level 9", state=DISABLED, padx=40)
level9.grid(row=3, column=2)

lvl_pg.mainloop()
